name: CI/CD Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 62.72.12.249 >> ~/.ssh/known_hosts

      - name: Deploy on VPS
        run: |
          ssh -i ~/.ssh/id_ed25519 deploy@62.72.12.249 "cd /home/deploy/app && git fetch origin main && git reset --hard origin/main && docker compose up -d --build"
